# Generated by Django 4.0.5 on 2022-06-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_api.path'),
        ),
    ]
